{{- $headless := include "rabbitmq-cluster.headlessServiceName" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq-cluster.fullname" . }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
data:
  enabled_plugins: |
    [rabbitmq_management].
  rabbitmq.conf: |
    cluster_name = {{ .Values.clusterName }}
    cluster_formation.peer_discovery_backend = classic_config
{{- range $index, $_ := until (int .Values.replicaCount) }}
    cluster_formation.classic_config.nodes.{{ add1 $index }} = rabbit@{{ include "rabbitmq-cluster.fullname" $ }}-{{ $index }}.{{ $headless }}.{{ $.Release.Namespace }}.svc.{{ $.Values.clusterDomain }}
{{- end }}
    cluster_formation.discovery_retry_limit = {{ .Values.rabbitmq.discoveryRetryLimit }}
    cluster_formation.discovery_retry_interval = {{ .Values.rabbitmq.discoveryRetryInterval }}
    cluster_partition_handling = {{ .Values.rabbitmq.clusterPartitionHandling }}
    queue_leader_locator = {{ .Values.rabbitmq.queueLeaderLocator }}
    loopback_users.guest = false
    listeners.tcp = none
    listeners.ssl.default = {{ .Values.service.amqps.port }}
    ssl_options.cacertfile = /etc/rabbitmq/tls/ca.crt
    ssl_options.certfile = /etc/rabbitmq/tls/tls.crt
    ssl_options.keyfile = /etc/rabbitmq/tls/tls.key
    ssl_options.verify = verify_none
    ssl_options.fail_if_no_peer_cert = false
    ssl_options.versions.1 = tlsv1.2
    management.ssl.port = {{ .Values.service.management.port }}
    management.ssl.cacertfile = /etc/rabbitmq/tls/ca.crt
    management.ssl.certfile = /etc/rabbitmq/tls/tls.crt
    management.ssl.keyfile = /etc/rabbitmq/tls/tls.key
    management.ssl.verify = verify_none
    management.ssl.fail_if_no_peer_cert = false
    management.ssl.versions.1 = tlsv1.2