apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq-cluster.authSecretName" . }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  erlang-cookie: {{ .Values.auth.erlangCookie | quote }}