apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq-cluster.fullname" . }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rabbitmq-cluster.selectorLabels" . | nindent 4 }}
  ports:
    - name: amqps
      port: {{ .Values.service.amqps.port }}
      targetPort: amqps
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.amqps.nodePort }}
      {{- end }}
    - name: mgmt-https
      port: {{ .Values.service.management.port }}
      targetPort: mgmt-https
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.management.nodePort }}
      {{- end }}